### ISSUE TITLE
Expose AssertMatches()

### ISSUE THREAD

**Issue by csilvers** [thejerf/slogassert#1]
Thank you for writing this!  We are looking from moving over from logrus to slog, and the lack of testing support is the main thing holding us back.

This library bridges a lot of that gap, but there are still some types of assertions we make that are not covered by this library.  We could request them all one by one, but it seems most useful -- to us and others -- if there was a low-level matcher that would allow us to write our own, custom matchers.

One idea is to make the existing `filter` function into an assertion:
```
func (h *Handler) AssertMatches(f func(LogMessage) bool) {
	matches := h.filter(func(lm LogMessage) (bool, bool) {
		matches := f(lm)
		return matches, !matches
	})
	if matches == 0 {
		h.t.Fatal("No logs matching filter were found")
	}
}
```
and a parallel AssertSomeMatches().

**Comment by thejerf** [comment]
Yeah, even as I wrote that I was wondering how smart it was to hide it, but on the principle of "easier to give than take away" I thought I'd try leaving it out. :)

**Comment by thejerf** [comment]
Thank you in general for the issues; it is always nice having other eyes and other experience brought to bear. Let me see what I can do here.
