### ISSUE TITLE
Provide `AssertFooN()`

### ISSUE THREAD

**Issue by csilvers** [thejerf/slogassert#2]
Right now, each assertion has two variants.  They each assert at least one message passes the relevant test, but one removes all such matches from the 'to be tested' messages and the other only removes the first.

This leaves us unable to make an assertion that we need frequently in our code: that a particular log message was _not_ logged.

I propose adding a third variant to each assertion, called `AssertFooN` (e.g. `AssertMessageN`).  It takes an extra arg which is how many matches are expected.  If some other number of matches is found, the matcher fails.  `AssertMessageN("message", 0)` would then let us assert that a message was never logged.

Conceivably, the uses of AssertSomeFoo and AssertFooN overlap enough that the first one could go away, and we'd have just AssertFoo and AssertFooN.  One possible API that could help with that would be to allow AssertFooN to take `-1` as the N value, meaning "all" (as in several go stdlib functions).  And AssertFooN would return how many matches it found, and you could make further assertions on that return value if you wanted to.  In particular, the assertion "retval is at least 1" would match the behavior of AssertSomeFoo.

**Comment by thejerf** [comment]
Yeah, I was noticing that in some of my own code too.

Another one I recently hit was wanting to assert a log message as _maybe_ being present; in my case, I have a log message that is normal in some testing environments but won't appear in all of them, and I'd like to note that it's normal and handled if present but that it's not mandatory.

I think I will opt for removing the current AssertSome mechanism, probably for one that specifies the exact number as you specify here, and another one that permits a range.
