### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by nbgraham** [thejerf/slogassert#8]
I'm enjoying this library, but would like to use the `New` constructor that accepts an interface.

I'd rather not pin an exact commit version in my go.mod.

https://github.com/thejerf/slogassert/commit/0ef72e755de72a047ef352a5d9ef82d521e696c5#diff-e84855bd78a66ae45838facb13ab7a2e1be7154973e74dea23824ce5604d0040

Cheers!

Edit:
Actually... maybe this won't help me. I'm trying to use a `*rapid.T`, but `testing.TB` has a `private` method.
https://pkg.go.dev/pgregory.net/rapid

Could this library use an interface that explicitly only requires the things that it needs?

**Comment by thejerf** [comment]
A fresh new v0.3.4 just for you. The testing interface is now just Helper(), which can be a no-op if your test system doesn't care about that, and Fatalf, which shouldn't be hard to shim around even if your system doesn't have that.

Thank you for the suggestion.
